#!/usr/bin/env bash
# One-time setup for a fresh Villa Saya server.
#
# Installs Docker, creates the deploy directory and writes a .env with freshly
# generated secrets. Run it once, as root, before the first deploy:
#
#   ssh root@your-server 'bash -s' < apps/villa-saya/deploy/bootstrap.sh
#
# Safe to re-run: it never overwrites an existing .env, because doing so would
# rotate the signing secrets and sign every user out.
set -euo pipefail

DEPLOY_PATH="${DEPLOY_PATH:-/opt/villa-saya}"
# A bare domain gets automatic HTTPS. Leave it empty to serve plain HTTP on the
# server's IP address.
APP_DOMAIN="${APP_DOMAIN:-}"

echo "==> Villa Saya bootstrap"
echo "    directory: $DEPLOY_PATH"
echo "    domain:    ${APP_DOMAIN:-(none, plain HTTP on this host IP)}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this as root." >&2
  exit 1
fi

# --- Docker -----------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo "==> Installing Docker"
  curl -fsSL https://get.docker.com | sh
else
  echo "==> Docker already installed ($(docker --version))"
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "The Docker Compose plugin is missing. Install docker-compose-plugin and re-run." >&2
  exit 1
fi

systemctl enable --now docker >/dev/null 2>&1 || true

# --- Firewall ---------------------------------------------------------------
# Only SSH and the web ports need to be reachable; the app itself is not
# published to the host at all.
if command -v ufw >/dev/null 2>&1; then
  echo "==> Configuring ufw"
  ufw allow 22/tcp  >/dev/null 2>&1 || true
  ufw allow 80/tcp  >/dev/null 2>&1 || true
  ufw allow 443/tcp >/dev/null 2>&1 || true
  ufw --force enable >/dev/null 2>&1 || true
fi

# --- Deploy directory and configuration -------------------------------------
mkdir -p "$DEPLOY_PATH"
cd "$DEPLOY_PATH"

if [ -f .env ]; then
  echo "==> .env already exists; leaving it untouched"
  echo "    (rewriting it would rotate the signing secrets and sign everyone out)"
else
  echo "==> Writing .env with freshly generated secrets"
  # Draw generously: stripping the non-alphanumeric base64 characters removes
  # an unpredictable number, and the result must still be a full 64 chars.
  gen() { head -c 256 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 64; }

  if [ -n "$APP_DOMAIN" ]; then
    app_url="https://$APP_DOMAIN"
    site_address="$APP_DOMAIN"
    cookie_secure="true"
  else
    # No domain means no certificate, and a Secure cookie would be dropped over
    # plain HTTP — sign-in would fail with nothing in the logs to explain it.
    ip="$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')"
    app_url="http://$ip"
    site_address=":80"
    cookie_secure="false"
  fi

  umask 077
  cat > .env <<ENVEOF
# Villa Saya — server configuration. Generated by bootstrap.sh.
# Keep this file private: it holds the token signing secrets.

NODE_ENV=production
APP_URL=$app_url
CADDY_SITE_ADDRESS=$site_address

# Rotating either secret signs every user out.
JWT_ACCESS_SECRET=$(gen)
JWT_REFRESH_SECRET=$(gen)

# Whether session cookies are marked Secure. Must be false without HTTPS.
COOKIE_SECURE=$cookie_secure

# Behind Caddy.
TRUST_PROXY=1

# Invitation emails. Without SMTP the link is written to the container log and
# returned in the UI for the inviter to pass on.
# SMTP_URL=smtp://user:pass@host:587
# MAIL_FROM="Villa Saya <no-reply@your-domain>"

# Set by the deploy workflow to the image currently rolled out.
ENVEOF
  chmod 600 .env
fi

echo
echo "==> Done."
echo
if [ -z "$APP_DOMAIN" ]; then
  cat <<'WARN'
    NOTE: no domain was given, so the app will serve plain HTTP and
    COOKIE_SECURE is off. Session cookies will travel unencrypted.
    Point a domain at this server and re-run with APP_DOMAIN=your-domain to
    switch on HTTPS, then set COOKIE_SECURE=true in .env.

WARN
fi
echo "    Next: push to main, or run the 'Villa Saya Deploy' workflow by hand."
